### PR TITLE
added GET /favorite endpoint to fetch cities

### PR DESCRIPTION
**Pull request by Abhinav-Bansal751**
# SOLVES #6 

## Description
- In this PR, I have added GET `/Favorites` endpoint to allow users to get his favoriteCities.
- As this will be a protected route so it will go through `auth` middleware and thus will have `userId` in its request Object.
- So we can use `Mongoose` `findbyId` api and then pass that userId to get the User object,and then return the favoriteCities List.

### CODE REVIEW

**Comment by nagcas** [comment]
You can delete the index.js file i would prefer to leave the server.js outside the src folder, at the moment both login and registration work, so let's do the pull request of the backend/src/routes/favorites.js file, Thanks a lot 😊

**Review by nagcas — APPROVED** [review]

**Comment by Abhinav-Bansal751** [comment]
I have deleted index.js in my local copy,now i have to make another commit ?and what changes should i do on favorites.js

**Review by nagcas — COMMENTED** [review]
I used the server.js file which is now in production, you can make changes to insert app.use favorites into this file.

**Review by nagcas — COMMENTED** [review]
in this file instead of using require you can use import, thanks again

**Pull request merged**
